apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditchecklistmodule-deployment
  labels:
    app: AuditChecklistModule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuditChecklistModule  
  template:
    metadata:
      labels:
        app: AuditChecklistModule
    spec:
      containers:
      - name: auditchecklistcr
        image: auditchecklistcr.azurecr.io/auditchecklistrepo:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: auditchecklistsvcsecret
---
apiVersion: v1
kind: Service
metadata:
  name: auditchecklistmodulesvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: AuditChecklistModule
